
name: "CI"

on:
  push:
    branches: [ master ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ master ]
 

jobs:
  build:
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    
    - name: Run a one-list script
      run: echo Hello, world!

    - name: Run a multi-line script
      run: |
	      echo Add other actions to build,
	      echo test, and deploy your project.